eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 3

spring:
  application:
    name: Api-Gateway-Service
  cloud:
    gateway:
      routes:
        - id: user-module
          uri: lb://USER-SERVICE
          predicates:
            - Path= /user/**
          filters:
            - RewritePath=/user(?<segment>.*), /$\{segment}
        - id: email-module
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path= /email/**
          filters:
            - RewritePath=/email(?<segment>.*), /$\{segment}
